---
- hosts: all
  remote_user: pi
  tasks:
    - name: Upload SSH Key
      authorized_key:
        user: pi
        state: present
        manage_dir: yes
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
